"""Add companies.news_checked_at + companies.website_funding_checked_at.

Revision ID: 0015
Revises: 0014
Create Date: 2026-06-12 00:30:00.000000

Rotation stamps for the two funding-news paths, so bounded daily runs cover
the whole table over several days instead of re-processing the same head
every day:

- news_checked_at: when ingest-news last ran this company's Google News RSS
  query. ORDER BY news_checked_at NULLS FIRST + LIMIT rotates the per-company
  sweep (2.6k RSS hits every day would eat half the private-repo Actions
  quota and invite a Google rate limit).
- website_funding_checked_at: when extract-funding-website last attempted
  this company (stamped even on "no funding found on site"). Most startup
  sites never state funding, so without a marker those companies stay
  eligible forever and the same alphabetical head gets re-LLM'd daily.

Hand-written rather than autogenerated: autogenerate also emitted DROPs for
hand-created objects it cannot model (trigram GIN index, partial indexes,
unique constraints) which must not be touched.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("news_checked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "website_funding_checked_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_index(
        "ix_companies_news_checked_at",
        "companies",
        ["news_checked_at"],
        unique=False,
    )
    op.create_index(
        "ix_companies_website_funding_checked_at",
        "companies",
        ["website_funding_checked_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_companies_website_funding_checked_at", table_name="companies")
    op.drop_index("ix_companies_news_checked_at", table_name="companies")
    op.drop_column("companies", "website_funding_checked_at")
    op.drop_column("companies", "news_checked_at")
