"""Add companies.status + companies.status_source_url.

Revision ID: 0016
Revises: 0015
Create Date: 2026-06-11 00:00:00.000000

Trust-correctness fix: VC portfolios list their exits, so acquired/dead
companies were rendering as live startups. ``status`` is one of
'active' | 'acquired' | 'shut_down' | 'ipo' (CHECK-enforced, same pattern as
ck_funding_rounds_extraction_confidence in 0007); extract-funding sets it from
explicit acquisition/shutdown/IPO announcements and never downgrades a
non-active value. ``status_source_url`` records the article (or company page)
that announced the event — every rendered fact needs a recorded source.

No index: status is not in any hot WHERE yet (the web's spotlight filter runs
over a handful of candidate ids).

Hand-written rather than autogenerated: autogenerate also emitted DROPs for
hand-created objects it cannot model (trigram GIN index, partial indexes,
unique constraints) which must not be touched.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("status", sa.String(), nullable=False, server_default="active"),
    )
    op.add_column(
        "companies",
        sa.Column("status_source_url", sa.String(), nullable=True),
    )
    op.create_check_constraint(
        "ck_companies_status",
        "companies",
        "status IN ('active', 'acquired', 'shut_down', 'ipo')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_companies_status", "companies", type_="check")
    op.drop_column("companies", "status_source_url")
    op.drop_column("companies", "status")
