"""Add companies.consecutive_scrape_failures.

Revision ID: 0017
Revises: 0016
Create Date: 2026-06-12 00:00:00.000000

Dead-site detection: scrape-homepages bumps this counter by one whenever a
company's homepage fetch is a total failure (network/HTTP error → no usable
content), resets it to 0 on a successful fetch, and leaves it unchanged on a
robots.txt block (the site is alive, just disallowing us). When the count
crosses a small threshold the web surfaces a muted "possibly inactive" rider —
a low-confidence signal, rendered deliberately quieter than the status badge.

No index: the counter is never used in a WHERE in the pipeline (it is only read
per-row on the detail page, which fetches the whole company row anyway).

Hand-written rather than autogenerated: autogenerate also emitted DROPs for
hand-created objects it cannot model (trigram GIN index, partial indexes,
unique constraints) which must not be touched.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column(
            "consecutive_scrape_failures",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )


def downgrade() -> None:
    op.drop_column("companies", "consecutive_scrape_failures")
