"""Add investors.slug (backfilled, NOT NULL, unique).

Revision ID: 0018
Revises: 0016
Create Date: 2026-06-12 00:00:00.000000

Powers the /investor/[slug] route. The pipeline owns slugs (consistent with
companies): upsert_investor assigns one at insert time, and this migration
backfills every existing row.

Three steps, all inside the one transactional DDL block:
  1. ADD COLUMN slug text NULL.
  2. Backfill: for each existing investor, slug = slugify(name), with a
     deterministic disambiguator seeded by the unique name_normalized when the
     base slug is already taken. Seeding from name_normalized (NOT os.urandom)
     makes the backfill reproducible and keeps it in lock-step with
     build_investor_slug in the live insert path.
  3. ALTER COLUMN slug SET NOT NULL + unique index.

NOTE (merge-time): the sibling dead-site PR landed migration 0017 first, so
down_revision is pinned to "0017" and the chain is linear 0016 -> 0017 -> 0018.
The filename stays 0018_investor_slug.py (0018 > 0017, single linear head).

Hand-written rather than autogenerated: autogenerate emits spurious DROPs for
hand-created objects (trigram GIN index, partial/unique indexes) it cannot
model, which must not be touched. This migration touches only investors.slug.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from nous.util.slugify import slug_with_disambiguator, slugify

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Minimal ad-hoc table for the core-level backfill — only the columns we read
# or write here. Avoids importing the ORM model (whose schema may drift ahead
# of this migration's point in history).
_investors = sa.table(
    "investors",
    sa.column("id", sa.Uuid()),
    sa.column("name", sa.String()),
    sa.column("name_normalized", sa.String()),
    sa.column("slug", sa.String()),
)


def _backfill_slugs(bind: sa.engine.Connection) -> None:
    """Compute and write a unique slug for every existing investor.

    Deterministic: base = slugify(name); on collision, seed the 6-hex
    disambiguator with name_normalized (unique per row), extending with a
    counter on the rare double-collision. Re-running yields the same slugs.
    """
    rows = bind.execute(
        sa.select(
            _investors.c.id,
            _investors.c.name,
            _investors.c.name_normalized,
            _investors.c.slug,
        ).order_by(_investors.c.name_normalized)
    ).all()

    # Idempotent mid-run: a prior (partial) run may have already written slugs
    # before failing. The unique index doesn't exist yet, so this `used` set is
    # the only collision guard. Seed it with every non-null slug already on disk
    # so we never re-issue one to a later row, and leave already-slugged rows
    # untouched (re-deriving could reassign them once `used` is pre-populated).
    used: set[str] = {row.slug for row in rows if row.slug is not None}
    for row in rows:
        if row.slug is not None:
            continue
        base = slugify(row.name) or "investor"
        candidate = base
        if candidate in used:
            seed = row.name_normalized or ""
            candidate = slug_with_disambiguator(base, seed)
            counter = 1
            while candidate in used:
                candidate = slug_with_disambiguator(base, seed + str(counter))
                counter += 1
        used.add(candidate)
        bind.execute(
            sa.update(_investors)
            .where(_investors.c.id == row.id)
            .values(slug=candidate)
        )


def upgrade() -> None:
    op.add_column(
        "investors",
        sa.Column("slug", sa.String(), nullable=True),
    )
    _backfill_slugs(op.get_bind())
    op.alter_column("investors", "slug", existing_type=sa.String(), nullable=False)
    op.create_index(
        op.f("ix_investors_slug"),
        "investors",
        ["slug"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_investors_slug"), table_name="investors")
    op.drop_column("investors", "slug")
