"""Add company_snapshots table (weekly time-series moat).

Revision ID: 0019
Revises: 0018
Create Date: 2026-06-12 12:00:00.000000

A weekly snapshot of each company's momentum signals — headcount range and
trailing-30-day news volume — keyed by the ISO-week Monday of capture. The
snapshot-companies stage upserts one row per company per week; the UNIQUE
(company_id, captured_week) is the idempotency key so a same-week re-run
refreshes values in place instead of appending.

Hand-written rather than autogenerated: autogenerate emits spurious DROPs for
hand-created objects (the trigram GIN index from migration 0003, partial /
unique indexes) it cannot model. This migration only creates the new table and
its indexes, touching nothing else.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "company_snapshots",
        sa.Column(
            "id",
            PG_UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "company_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("companies.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("captured_week", sa.Date(), nullable=False),
        sa.Column("employee_count_min", sa.Integer(), nullable=True),
        sa.Column("employee_count_max", sa.Integer(), nullable=True),
        sa.Column(
            "news_count_30d",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "company_id",
            "captured_week",
            name="uq_company_snapshots_company_week",
        ),
    )
    op.create_index(
        "ix_company_snapshots_company_id",
        "company_snapshots",
        ["company_id"],
    )
    op.create_index(
        "ix_company_snapshots_captured_week",
        "company_snapshots",
        ["captured_week"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_company_snapshots_captured_week",
        table_name="company_snapshots",
    )
    op.drop_index(
        "ix_company_snapshots_company_id",
        table_name="company_snapshots",
    )
    op.drop_table("company_snapshots")
