"""P2 schema hardening: forbid self-referential competitors + drop duplicate news url index.

Revision ID: 0020
Revises: 0019
Create Date: 2026-06-12 13:00:00.000000

Two small, independent fixes:

1. competitors: add CHECK ck_competitors_no_self_reference so a company can
   never be listed as its own competitor (competitor_company_id == company_id).
   Defensively delete any pre-existing self-referential rows first (set-based)
   so the constraint applies cleanly even against dirty data.

2. news_articles: drop the redundant ix_news_articles_url index. The column
   already carries a unique index via the uq_news_articles_url UNIQUE
   constraint (created in migration 0003); ix_news_articles_url was a second,
   identical UNIQUE btree(url) emitted by a stray index=True on the model.
   One unique index over `url` is enough.

Hand-written rather than autogenerated: autogenerate emits spurious DROPs for
hand-created objects (trigram GIN, partial indexes) it cannot model. This
migration touches only the two objects above.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. competitors: scrub any self-referential rows, then forbid them.
    op.execute(
        "DELETE FROM competitors WHERE competitor_company_id = company_id"
    )
    op.create_check_constraint(
        "ck_competitors_no_self_reference",
        "competitors",
        "competitor_company_id IS NULL OR competitor_company_id <> company_id",
    )

    # 2. news_articles: drop the duplicate unique index, keeping the one that
    #    backs the uq_news_articles_url constraint.
    op.drop_index("ix_news_articles_url", table_name="news_articles")


def downgrade() -> None:
    # Recreate the duplicate unique index, then drop the CHECK.
    op.create_index(
        "ix_news_articles_url",
        "news_articles",
        ["url"],
        unique=True,
    )
    op.drop_constraint(
        "ck_competitors_no_self_reference",
        "competitors",
        type_="check",
    )
