"""Add companies.total_raised_usd + its source/as-of attribution columns.

Revision ID: 0021
Revises: 0020
Create Date: 2026-06-12 00:00:00.000000

Hybrid "total raised" fix: news discovery has a 7-day lookback and historical
rounds are never backfilled, so summing funding_rounds undercounts any company
with a pre-nous funding history (e.g. Fresha's TechCrunch coverage says "has
now raised $285 million to date" while we hold a single $80M round). Articles
often state the cumulative figure outright, so record it when they do:

- ``total_raised_usd`` — the stated cumulative total from an article (or the
  company's own site), distinct from the sum of funding_rounds rows. Same
  NUMERIC(20,2) scale as funding_rounds.amount_raised.
- ``total_raised_source_url`` — the article/page that stated the figure;
  every fact rendered on a company page needs a recorded source.
- ``total_raised_as_of`` — the stating article's published date, giving
  newest-article-wins semantics when claims conflict.

extract-funding applies all three together (see _apply_total_raised); the web
tile shows max(stated, sum-of-rounds) with attribution when the stated value
is displayed.

No index: the columns appear in no hot WHERE — the --requery-totals backfill
filter is a one-time manual lever, not a scheduled query.

Hand-written rather than autogenerated: autogenerate emits spurious DROPs for
hand-created objects (trigram GIN, partial indexes) it cannot model.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("total_raised_usd", sa.Numeric(20, 2), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("total_raised_source_url", sa.Text(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("total_raised_as_of", sa.Date(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("companies", "total_raised_as_of")
    op.drop_column("companies", "total_raised_source_url")
    op.drop_column("companies", "total_raised_usd")
