"""Catalog quality filtering: soft exclusion + content-bar columns.

Revision ID: 0022
Revises: 0021
Create Date: 2026-06-12 00:00:00.000000

Per docs/superpowers/specs/2026-06-12-catalog-quality-filtering-design.md:

- ``exclusion_reason`` / ``exclusion_detail`` / ``excluded_at`` — soft
  exclusion with an audit trail. NULL reason = included. Soft (not DELETE)
  because weekly portfolio re-discovery would resurrect deleted rows.
- ``eligibility_checked_at`` — stamp for the is-this-a-startup judgment so
  the judge-eligibility backfill visits each enriched row exactly once.
- ``rejected_urls`` — JSONB list of URLs confirmed wrong for the company
  (parked/for-sale domains); resolve-homepages skips these domains.
- ``funding_round_count`` — denormalized count(funding_rounds), backfilled
  below, so the web catalog bar is a flat indexed WHERE instead of an OR
  over an EXISTS that PostgREST cannot express with pagination.

Hand-written rather than autogenerated: autogenerate emits spurious DROPs
for hand-created objects (trigram GIN, partial indexes) it cannot model.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies", sa.Column("exclusion_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("exclusion_detail", sa.Text(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("excluded_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "eligibility_checked_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "rejected_urls",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "funding_round_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.create_check_constraint(
        "ck_companies_exclusion_reason",
        "companies",
        "exclusion_reason IN ('parse_artifact', 'non_us', 'not_a_startup', 'manual') "
        "OR exclusion_reason IS NULL",
    )
    op.create_index(
        "ix_companies_exclusion_reason", "companies", ["exclusion_reason"]
    )
    op.create_index(
        "ix_companies_eligibility_checked_at",
        "companies",
        ["eligibility_checked_at"],
    )
    op.create_index(
        "ix_companies_funding_round_count", "companies", ["funding_round_count"]
    )

    # Backfill the denormalized round count from existing data.
    op.execute(
        """
        UPDATE companies
        SET funding_round_count = sub.cnt
        FROM (
            SELECT company_id, count(*) AS cnt
            FROM funding_rounds
            GROUP BY company_id
        ) AS sub
        WHERE companies.id = sub.company_id
        """
    )


def downgrade() -> None:
    op.drop_index("ix_companies_funding_round_count", table_name="companies")
    op.drop_index("ix_companies_eligibility_checked_at", table_name="companies")
    op.drop_index("ix_companies_exclusion_reason", table_name="companies")
    op.drop_constraint(
        "ck_companies_exclusion_reason", "companies", type_="check"
    )
    op.drop_column("companies", "funding_round_count")
    op.drop_column("companies", "rejected_urls")
    op.drop_column("companies", "eligibility_checked_at")
    op.drop_column("companies", "excluded_at")
    op.drop_column("companies", "exclusion_detail")
    op.drop_column("companies", "exclusion_reason")
