"""company_relationships edge table

Revision ID: 0022
Revises: 0021
Create Date: 2026-06-12 00:00:00.000000

Adds the unified company<->company relationship graph behind the "Related
companies" surface:
- company_relationships table (one row per directed company->related edge)
- UNIQUE (company_id, related_company_id, relationship_type) — the idempotency
  key for the replace-style derive-relationships stage
- CHECK related_company_id <> company_id (no self-edges; mirrors competitors)
- CHECK relationship_type in the allowed set (competitor/similar reserved for
  derive-relationships; supplier/customer/partner reserved for a future pass)
- indexes on company_id (primary access path), related_company_id (reverse
  lookups), relationship_type (filtering by edge kind)

id carries a gen_random_uuid() server default (PG13+ built-in, already used by
0019) so the set-based INSERT ... SELECT in derive-relationships need not supply
the primary key; ORM inserts still provide it via the model's uuid4 default.

Hand-written (not autogenerated) per the 0015-0021 convention so autogenerate's
spurious DROPs of the pg_trgm/partial indexes elsewhere don't sneak in.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "company_relationships",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "related_company_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("relationship_type", sa.String(), nullable=False),
        sa.Column("score", sa.Numeric(6, 3), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("evidence", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            ondelete="CASCADE",
            name="fk_company_relationships_company_id",
        ),
        sa.ForeignKeyConstraint(
            ["related_company_id"],
            ["companies.id"],
            ondelete="CASCADE",
            name="fk_company_relationships_related_company_id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "related_company_id",
            "relationship_type",
            name="uq_company_relationships_pair_type",
        ),
        sa.CheckConstraint(
            "related_company_id <> company_id",
            name="ck_company_relationships_no_self",
        ),
        sa.CheckConstraint(
            "relationship_type IN "
            "('competitor', 'similar', 'supplier', 'customer', 'partner')",
            name="ck_company_relationships_type",
        ),
    )
    op.create_index(
        "ix_company_relationships_company_id",
        "company_relationships",
        ["company_id"],
    )
    op.create_index(
        "ix_company_relationships_related_company_id",
        "company_relationships",
        ["related_company_id"],
    )
    op.create_index(
        "ix_company_relationships_relationship_type",
        "company_relationships",
        ["relationship_type"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_company_relationships_relationship_type",
        table_name="company_relationships",
    )
    op.drop_index(
        "ix_company_relationships_related_company_id",
        table_name="company_relationships",
    )
    op.drop_index(
        "ix_company_relationships_company_id",
        table_name="company_relationships",
    )
    op.drop_table("company_relationships")
