"""Add companies.hq_country_checked_at.

Revision ID: 0029
Revises: 0028
Create Date: 2026-06-15 00:00:00.000000

Rotation/back-off stamp for the infer-hq-country repair stage: when that stage
last attempted a company (success or not). A bounded, dispatch-gated run drains
the shown + hq_country IS NULL backlog over successive dispatches; a row that
yielded no country is stamped so it is not re-fetched. Mirrors the existing
*_checked_at stamps (news_checked_at, website_funding_checked_at).

Hand-written (not autogenerated) so autogenerate's spurious DROPs for
hand-created objects (trigram GIN index, partial indexes) are not emitted.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0029"
down_revision: str | None = "0028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column(
            "hq_country_checked_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_index(
        "ix_companies_hq_country_checked_at",
        "companies",
        ["hq_country_checked_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_companies_hq_country_checked_at", table_name="companies"
    )
    op.drop_column("companies", "hq_country_checked_at")
