"""Index the companies filter columns used by the web browse/location/tag pages.

Revision ID: 0030
Revises: 0029
Create Date: 2026-06-16 00:00:00.000000

Four ``companies`` columns appear in web ``WHERE`` clauses / facets but were
never indexed, so each filtered query fell back to a sequential scan:

- ``hq_state``       — equality on the /location pages and the location filter.
- ``tags``           — array containment (``@>`` / overlap) on the /tag pages
                       and the tag filter; needs a **GIN** index, not btree.
- ``industry_group`` — equality filter and the industry facet on /companies.
- ``discovered_via`` — the discovery-source filter on /companies.

Per the project convention "index every column used in a WHERE", this adds a
btree index for the three scalar equality columns and a GIN index for the
``tags`` array. Pure index DDL — no data change, fully reversible.

Hand-written rather than autogenerated, per the 0015+ convention: autogenerate
emits spurious DROPs for hand-created objects (the ``normalized_name`` trigram
GIN index, partial indexes) it cannot model.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0030"
down_revision: str | None = "0029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_index(
        "ix_companies_hq_state",
        "companies",
        ["hq_state"],
        unique=False,
    )
    op.create_index(
        "ix_companies_tags",
        "companies",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_companies_industry_group",
        "companies",
        ["industry_group"],
        unique=False,
    )
    op.create_index(
        "ix_companies_discovered_via",
        "companies",
        ["discovered_via"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_companies_discovered_via", table_name="companies")
    op.drop_index("ix_companies_industry_group", table_name="companies")
    op.drop_index("ix_companies_tags", table_name="companies")
    op.drop_index("ix_companies_hq_state", table_name="companies")
