"""Stamp LLM-derived rows with the prompt version that produced them.

Revision ID: 0031
Revises: 0030
Create Date: 2026-07-10 00:00:00.000000

Every prompt module that persists data now carries a ``PROMPT_VERSION``
constant (bumped on any semantic change). The writing stages stamp it onto the
rows they produce, so data written by a bad prompt revision can be found
("WHERE <family>_prompt_version = 'X'") and selectively re-run instead of
re-running everything.

``companies`` holds LLM output from four different prompt families, so it gets
one column per family rather than a single ambiguous stamp:

- ``enrichment_prompt_version``  — description/tags/category/people/hq fields
                                   (enrich-companies, company_description prompt).
- ``eligibility_prompt_version`` — the is-startup judgment, from whichever
                                   prompt made the CURRENT call: company_description
                                   on the enrich path, company_eligibility on the
                                   judge-eligibility backfill.
- ``hq_country_prompt_version``  — hq_country set by infer-hq-country
                                   (hq_country prompt).
- ``funding_prompt_version``     — status / total_raised_* applied by
                                   extract-funding (funding_extraction prompt).

``funding_rounds.prompt_version`` and ``competitors.prompt_version`` stamp
those tables' rows (single-prompt tables, so one plain column each).

All columns are nullable TEXT with NO backfill: NULL means "produced before
prompt versioning existed" (or never LLM-touched), which is itself a useful
re-run cohort. Deliberately NOT indexed: no pipeline stage or web query
filters on them — only rare ad-hoc re-run queries do, and a sequential scan
at this table size is fine (per-WHERE indexing applies to recurring query
paths, not one-off operational sweeps).

Hand-written rather than autogenerated, per the 0015+ convention: autogenerate
emits spurious DROPs for hand-created objects (the ``normalized_name`` trigram
GIN index, partial indexes) it cannot model.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0031"
down_revision: str | None = "0030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("enrichment_prompt_version", sa.Text(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("eligibility_prompt_version", sa.Text(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("hq_country_prompt_version", sa.Text(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("funding_prompt_version", sa.Text(), nullable=True),
    )
    op.add_column(
        "funding_rounds",
        sa.Column("prompt_version", sa.Text(), nullable=True),
    )
    op.add_column(
        "competitors",
        sa.Column("prompt_version", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("competitors", "prompt_version")
    op.drop_column("funding_rounds", "prompt_version")
    op.drop_column("companies", "funding_prompt_version")
    op.drop_column("companies", "hq_country_prompt_version")
    op.drop_column("companies", "eligibility_prompt_version")
    op.drop_column("companies", "enrichment_prompt_version")
