"""slug_aliases: dead company slugs permanently redirecting to survivors.

Revision ID: 0032
Revises: 0031
Create Date: 2026-07-10 00:00:00.000000

Dedup merges (``merge_companies``) DELETE the loser company row, killing its
slug — inbound links and accrued SEO equity 404. This table records the
loser's slug at merge time pointing at the surviving company; the web layer
308-redirects ``/c/<old_slug>`` to the survivor's current slug, looking the
alias up only when the live-slug fetch misses (valid slugs pay zero extra
queries, and a live slug always shadows a stale alias).

``old_slug`` is the natural primary key — a deliberate exception to the
surrogate-UUID house convention. The PK *is* the invariant (a dead slug
aliases exactly one survivor) and the upsert conflict target that makes merge
chains converge: merging A→B then B→C re-targets A's alias to C via
ON CONFLICT (old_slug) DO UPDATE.

``company_id`` is ON DELETE CASCADE: a company deleted outside the merge path
takes its aliases with it rather than leaving redirects to a 404. The merge
path repoints the loser's aliases to the survivor BEFORE deleting the loser,
so alias chains survive merges — the cascade is only a backstop. The column is
indexed: it's an FK, and the merge repoint filters WHERE company_id = loser.

RLS is enabled with no policies, matching migration 0027's defense-in-depth:
the web app reads via service_role and the pipeline connects as table owner
(both bypass RLS), while the anon/authenticated PostgREST roles see nothing.

Hand-written rather than autogenerated, per the 0015+ convention: autogenerate
emits spurious DROPs for hand-created objects (the ``normalized_name`` trigram
GIN index, partial indexes) it cannot model.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0032"
down_revision: str | None = "0031"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "slug_aliases",
        sa.Column("old_slug", sa.Text(), primary_key=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            ondelete="CASCADE",
            name="fk_slug_aliases_company_id",
        ),
    )
    op.create_index(
        "ix_slug_aliases_company_id",
        "slug_aliases",
        ["company_id"],
    )
    op.execute("ALTER TABLE slug_aliases ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    op.drop_index("ix_slug_aliases_company_id", table_name="slug_aliases")
    # Dropping the table drops its FK and RLS state with it.
    op.drop_table("slug_aliases")
