"""Company description embeddings (pgvector) + the similar_companies RPC.

Revision ID: 0033
Revises: 0032
Create Date: 2026-07-11 00:00:00.000000

Wave 3 (E-1): the W-F describe pass made ``description_short`` /
``description_long`` rich enough to be worth embedding. The embed-companies
stage computes a 384-dim sentence embedding (fastembed, BAAI/bge-small-en-v1.5,
CPU/ONNX — $0 LLM cost) over ``name + description_short + description_long``
for shown companies, and the web's similar-companies module ranks neighbors by
cosine distance through the ``similar_companies`` SQL function below.

``CREATE EXTENSION vector``: pgvector ships on the Supabase free tier (it is
in Supabase's allowed-extensions list on every plan) and in CI via the
``pgvector/pgvector:pg15`` service image (plain ``postgres:15`` does NOT bundle
it — lint.yml's service image was switched in this same change). IF NOT EXISTS
because a dashboard-enabled extension may already exist; Supabase's database
search_path includes both ``public`` and ``extensions``, so the unqualified
``vector`` type resolves wherever the extension landed.

Columns (all nullable — NULL means "not embedded yet", and the web renders no
similar-companies section for such rows rather than fabricating one):

- ``embedding vector(384)``    — bge-small-en-v1.5 output dimension.
- ``embedded_at timestamptz``  — when the current embedding was computed.
- ``embedding_text_hash text`` — sha256 of the exact text embedded; the
                                 idempotence key. The stage re-embeds only when
                                 the recomputed hash differs, so unchanged
                                 descriptions cost nothing on re-runs.

Deliberately NO vector index: at the current catalog size (~3k companies) an
exact sequential scan over 384-dim vectors is ~single-digit milliseconds,
and both ivfflat and hnsw trade recall/build-time for speed we don't need.
Revisit around ~50–100k embedded rows (or when the similar-companies query's
p95 visibly degrades): at that point add an ``hnsw (embedding
vector_cosine_ops)`` index — hnsw over ivfflat because rows arrive
incrementally and ivfflat lists would need periodic re-clustering.
``embedding_text_hash`` is likewise unindexed: the stage's selection predicate
(hash mismatch OR embedding IS NULL) is a full-catalog comparison against a
per-row computed value, not an indexable equality probe.

``similar_companies(company_id, match_count)`` is the read path for the web:
supabase-js cannot ORDER BY a vector distance through PostgREST filters, so
the ordering lives in this STABLE SQL function and the web calls it via
``.rpc()``. It self-excludes the anchor row, returns only shown
(``exclusion_reason IS NULL``) companies that themselves have an embedding —
so excluded companies never surface — and returns the card columns plus the
cosine similarity so the UI can disclose ranking strength. SECURITY INVOKER
(the default) on purpose: the web calls it as ``service_role`` (bypasses RLS);
if the anon PostgREST role ever invoked it, companies' RLS
(enabled-with-no-policies, migration 0027) yields zero rows rather than a
data leak.

Hand-written rather than autogenerated, per the 0015+ convention: autogenerate
emits spurious DROPs for hand-created objects (the ``normalized_name`` trigram
GIN index, partial indexes) it cannot model — and it cannot emit CREATE
EXTENSION or CREATE FUNCTION at all.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "0033"
down_revision: str | None = "0032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The web's nearest-neighbor read path. SQL-language + STABLE so Postgres can
# inline/plan it per call; casts to text because the underlying columns are
# varchar and SQL-language functions require exact return-type matches.
_SIMILAR_COMPANIES_FN = """
CREATE FUNCTION similar_companies(company_id uuid, match_count integer DEFAULT 6)
RETURNS TABLE (
    id uuid,
    slug text,
    name text,
    logo_url text,
    description_short text,
    industry_group text,
    similarity double precision
)
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
    SELECT
        c.id,
        c.slug::text,
        c.name::text,
        c.logo_url::text,
        c.description_short::text,
        c.industry_group::text,
        1 - (c.embedding <=> src.embedding) AS similarity
    FROM companies c,
         (SELECT embedding
            FROM companies
           WHERE companies.id = similar_companies.company_id
             AND embedding IS NOT NULL) AS src
    WHERE c.id <> similar_companies.company_id
      AND c.embedding IS NOT NULL
      AND c.exclusion_reason IS NULL
    ORDER BY c.embedding <=> src.embedding
    LIMIT match_count
$$;
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column(
        "companies",
        sa.Column("embedding", Vector(384), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("embedding_text_hash", sa.Text(), nullable=True),
    )
    op.execute(_SIMILAR_COMPANIES_FN)


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS similar_companies(uuid, integer);")
    op.drop_column("companies", "embedding_text_hash")
    op.drop_column("companies", "embedded_at")
    op.drop_column("companies", "embedding")
    # Nothing else in the schema uses the vector type once the column is gone.
    # IF EXISTS keeps the downgrade re-runnable; this will (correctly) fail if
    # some future object outside this migration's knowledge depends on it.
    op.execute("DROP EXTENSION IF EXISTS vector;")
