"""Themes: clustered market segments over the company embeddings (E-3).

Revision ID: 0034
Revises: 0033
Create Date: 2026-07-11 00:00:00.000000

Wave 3 (E-3): the compute-themes stage clusters the 0033 description
embeddings per ``industry_group`` (KMeans over shown + embedded companies),
names each coherent cluster with one DeepSeek call, and materializes the
result here for the /themes pages. Two tables:

``themes`` — one row per named cluster:

- ``slug`` (unique)      — URL key for /themes/[slug]. Kept stable across
                           re-runs by matching new cluster centroids to the
                           previous run's centroids at cosine ≥ 0.9 (see the
                           stage docstring for the tolerance rationale).
- ``name``               — LLM-authored display name (2–5 words).
- ``industry_group``     — the industry the cluster was computed within.
                           Indexed: the stage's replace-per-industry writes
                           and centroid-match reads both filter on it.
- ``description``        — LLM-authored one-sentence description. Nullable —
                           the prompt returns null rather than fabricate, and
                           an incoherent cluster is dropped before insert, so
                           in practice this is set; nullable keeps the schema
                           honest about the LLM boundary.
- ``centroid vector(384)`` — unit-normalized mean of member embeddings; the
                           slug-stability anchor for the next run. Same
                           dimension as companies.embedding (0033); same
                           no-vector-index decision (a handful of themes per
                           industry — exact scan is trivially cheap).
- ``company_count``      — member count at build time (shown companies only).
                           The sitemap's ≥3-member threshold reads this.
- Funding metrics, all computed at build time by the stage from the member
  companies' ``funding_rounds.announced_date`` / ``amount_raised`` (derived
  from stored, sourced rounds — never a new unattributed number):
  - ``funding_recent_usd``  — sum over the 2 most recent COMPLETE calendar
                              quarters as of the run date.
  - ``funding_prior_usd``   — sum over the 2 quarters before those.
  - ``funding_growth``      — (recent − prior) / prior, the /themes ranking
                              key. NULL when prior is 0 (a growth rate over a
                              zero base is undefined — the web renders "new
                              funding" / "—" from the two sums instead of a
                              fabricated infinity). Nullable Numeric, ordered
                              NULLS LAST.
- ``prompt_version``     — theme_naming.PROMPT_VERSION that authored
                           name/description (0031 convention). Preserved when
                           a centroid-matched theme keeps its previous name
                           without a new LLM call.

``company_themes`` — theme membership, replace-style per theme:

- ``theme_id`` / ``company_id`` FKs, both ON DELETE CASCADE (a deleted theme
  or a dedup-merged company takes its memberships with it), both indexed
  (house rule: index every FK; the web reads WHERE theme_id = X, the stage
  rewrites by theme_id).
- ``similarity`` — cosine similarity of the member's embedding to the theme
  centroid; the web's member ordering. Double precision (matches the 0033
  RPC's similarity output; it's a display/ordering signal, not money).
- UNIQUE (theme_id, company_id) — the idempotency key: a re-run's
  replace-style rewrite can never double-link a member.

RLS enabled with NO policies on both tables, exactly like migration 0027:
the web reads via service_role (bypasses RLS), the pipeline connects as the
table owner (bypasses RLS), and the anon/authenticated PostgREST roles are
denied all rows.

Hand-written rather than autogenerated, per the 0015+ convention:
autogenerate emits spurious DROPs for hand-created objects (the
``normalized_name`` trigram GIN index, partial indexes) it cannot model.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

# revision identifiers, used by Alembic.
revision: str = "0034"
down_revision: str | None = "0033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "themes",
        sa.Column("id", PG_UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("industry_group", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("centroid", Vector(384), nullable=False),
        sa.Column("company_count", sa.Integer(), nullable=False),
        sa.Column(
            "funding_recent_usd",
            sa.Numeric(20, 2),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "funding_prior_usd",
            sa.Numeric(20, 2),
            nullable=False,
            server_default="0",
        ),
        sa.Column("funding_growth", sa.Numeric(12, 4), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("slug", name="uq_themes_slug"),
    )
    # industry_group backs the stage's per-industry replace/centroid-match
    # queries and any future industry-scoped web listing.
    op.create_index("ix_themes_industry_group", "themes", ["industry_group"])

    op.create_table(
        "company_themes",
        sa.Column("id", PG_UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "theme_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("themes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "company_id",
            PG_UUID(as_uuid=True),
            sa.ForeignKey("companies.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "theme_id", "company_id", name="uq_company_themes_theme_company"
        ),
    )
    op.create_index("ix_company_themes_theme_id", "company_themes", ["theme_id"])
    op.create_index("ix_company_themes_company_id", "company_themes", ["company_id"])

    # Defense-in-depth, 0027 pattern: service_role/table-owner access is
    # unaffected; anon/authenticated PostgREST roles see zero rows.
    op.execute("ALTER TABLE themes ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE company_themes ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    # company_themes first (it FKs themes). RLS drops with the tables.
    op.drop_index("ix_company_themes_company_id", table_name="company_themes")
    op.drop_index("ix_company_themes_theme_id", table_name="company_themes")
    op.drop_table("company_themes")
    op.drop_index("ix_themes_industry_group", table_name="themes")
    op.drop_table("themes")
