"""The semantic_companies RPC: query-embedding search for /companies (E-2).

Revision ID: 0035
Revises: 0034
Create Date: 2026-07-11 00:00:00.000000

Wave 3 (E-2): semantic search over the 0033 description embeddings. The web
embeds the user's search query server-side (transformers.js, the same
bge-small-en-v1.5 family the pipeline stores — CLS-pooled, normalized; see
web/lib/embed-query.ts) and passes the resulting 384-dim vector here.
PostgREST cannot ORDER BY a vector distance through filter params, so — like
``similar_companies`` (0033) — the cosine ranking lives in this STABLE SQL
function and the web calls it via ``.rpc()``.

Differences from ``similar_companies``: the anchor is a caller-supplied query
embedding rather than another company's stored vector, so there is no
self-exclusion and no anchor lookup; and the returned columns mirror the
/companies card-list projection (what ``listCompanies`` selects: slug, name,
hq_city, hq_state, industry_group, description_short, status, logo_url) plus
the cosine similarity, because the results render as ordinary CompanyCards in
the browse grid.

Filters match ``similar_companies``: only shown (``exclusion_reason IS
NULL``) companies that have an embedding. ``embedding IS NOT NULL`` implies
the catalog bar's description arm by stage invariant (embed-companies only
embeds described companies), but the bar's
``description_short IS NOT NULL OR funding_round_count > 0`` is applied
explicitly anyway — defense in depth so a future change to the embed stage's
selection can't silently start surfacing bar-failing rows in search.

``match_count`` defaults to 30 — the /companies page size; the caller passes
it explicitly so the SQL default and the UI cap can't drift apart silently
(same convention as SIMILAR_COMPANIES_LIMIT).

SECURITY INVOKER (the default) on purpose, same reasoning as 0033: the web
calls this as ``service_role`` (bypasses RLS); if the anon PostgREST role
ever invoked it, companies' RLS (enabled-with-no-policies, migration 0027)
yields zero rows rather than a data leak.

No schema changes — models.py is untouched; this migration only creates (and
on downgrade drops) the function.

Hand-written rather than autogenerated, per the 0015+ convention: autogenerate
emits spurious DROPs for hand-created objects (the ``normalized_name`` trigram
GIN index, partial indexes) it cannot model — and it cannot emit CREATE
FUNCTION at all.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0035"
down_revision: str | None = "0034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The web's semantic-search read path. SQL-language + STABLE so Postgres can
# inline/plan it per call; casts to text because the underlying columns are
# varchar and SQL-language functions require exact return-type matches.
_SEMANTIC_COMPANIES_FN = """
CREATE FUNCTION semantic_companies(query_embedding vector(384), match_count integer DEFAULT 30)
RETURNS TABLE (
    slug text,
    name text,
    hq_city text,
    hq_state text,
    industry_group text,
    description_short text,
    status text,
    logo_url text,
    similarity double precision
)
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
    SELECT
        c.slug::text,
        c.name::text,
        c.hq_city::text,
        c.hq_state::text,
        c.industry_group::text,
        c.description_short::text,
        c.status::text,
        c.logo_url::text,
        1 - (c.embedding <=> query_embedding) AS similarity
    FROM companies c
    WHERE c.embedding IS NOT NULL
      AND c.exclusion_reason IS NULL
      AND (c.description_short IS NOT NULL OR c.funding_round_count > 0)
    ORDER BY c.embedding <=> query_embedding
    LIMIT match_count
$$;
"""


def upgrade() -> None:
    op.execute(_SEMANTIC_COMPANIES_FN)


def downgrade() -> None:
    op.execute(
        "DROP FUNCTION IF EXISTS semantic_companies(vector, integer);"
    )
