"""Add website provenance + fallback-resolver rotation stamp to companies.

Revision ID: 0037
Revises: 0036
Create Date: 2026-07-13 00:00:00.000000

Two concerns for the new ``resolve-website-fallback`` stage (husk re-mining).

**Website provenance.** Until now a resolved ``website`` carried no record of
where it came from: a blind ``{slug}{tld}`` guess (resolve-homepages), an
authoritative VC-portfolio link, and a re-mined Wikidata "official website" were
all indistinguishable. The fallback stage introduces the first per-website
provenance record, and the every-fact-has-a-source rule (CLAUDE.md) requires it.
Mirrors the sibling-column convention used for ``status``/``status_source_url``
and ``total_raised_usd``/``total_raised_source_url``:

- ``website_source``     — short source-type tag ('wikidata' | 'news_outbound' |
  …). Low cardinality; feeds the data-quality dashboard's "where did our
  websites come from" breakdown. NULL for the legacy cohort.
- ``website_source_url`` — the specific attributing URL (the Wikidata entity
  page, the sourcing news article). The auditable citation.

Both nullable, un-indexed: never used in a WHERE, only read for display.

**Fallback rotation stamp.** ``website_fallback_checked_at`` is the fallback
stage's own attempt timestamp — deliberately separate from
``website_resolved_at`` (which resolve-homepages stamps). Sharing one stamp
would make a husk resolve-homepages *just* failed on invisible to the fallback
for 90 days; a dedicated stamp lets the two resolvers rotate independently.
Mirrors the other *_checked_at back-off stamps (news_checked_at,
website_funding_checked_at, hq_country_checked_at). Indexed — it drives the
fallback stage's selection WHERE/ORDER.

Hand-written (not autogenerated) so autogenerate's spurious DROPs for
hand-created objects (trigram GIN index, partial indexes) are not emitted.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0037"
down_revision: str | None = "0036"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("website_source", sa.Text(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("website_source_url", sa.Text(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "website_fallback_checked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_companies_website_fallback_checked_at",
        "companies",
        ["website_fallback_checked_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_companies_website_fallback_checked_at", table_name="companies"
    )
    op.drop_column("companies", "website_fallback_checked_at")
    op.drop_column("companies", "website_source_url")
    op.drop_column("companies", "website_source")
