"""Company market-map coordinates (per-industry PCA projection).

Revision ID: 0038
Revises: 0037
Create Date: 2026-07-13 00:00:00.000000

The compute-map-positions stage fits scikit-learn PCA(n_components=2) over each
industry_group's shown + embedded companies' description embeddings (migration
0033), projects to 2D, pins a deterministic sign convention, and min-max
normalizes each axis to [0, 1] WITHIN the industry cohort. The web renders a
static SVG scatter at /map/[industry] from these coords.

Stored as three nullable columns ON companies rather than a side table: coords
are strictly 1:1 with a company (one position, projected in its own
industry_group's PCA basis). A side table would add a join + FK for no
cardinality benefit; the dominant read — every positioned company in one
industry — is a flat single-table WHERE (industry_group = $1 AND
map_x IS NOT NULL), PostgREST-friendly with no RPC, mirroring the latest_round_*
denormalization (0028). Node-sizing inputs (latest_round_amount,
funding_round_count) already live on companies, so the whole map row is one read.

- map_x / map_y (double precision, nullable) — normalized [0, 1] cohort coords.
  NULL = not positioned (industry below MIN_MAP_COMPANIES, or no embedding yet);
  the web draws no node.
- map_computed_at (timestamptz, nullable) — per-company freshness stamp; the
  stage's per-industry TTL gate reads MAX(map_computed_at) over a cohort to skip
  freshly-mapped industries (monthly cadence via the weekly discovery workflow).

Coords are only comparable WITHIN an industry_group (own PCA basis + independent
min-max) — exactly the /map/[industry] read grain; the cohort key
(industry_group) already travels on the row.

Deliberately NO index: map_x/map_y are never a selective WHERE key — the read
filters the already-indexed industry_group and treats map_x IS NOT NULL as a
NOT-NULL predicate within that partition; the TTL gate's MAX(map_computed_at) is
a small per-industry scan (same call as embedding_text_hash in 0033).

Hand-written (not autogenerated) per the 0015+ convention.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0038"
down_revision: str | None = "0037"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("companies", sa.Column("map_x", sa.Float(), nullable=True))
    op.add_column("companies", sa.Column("map_y", sa.Float(), nullable=True))
    op.add_column(
        "companies",
        sa.Column("map_computed_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("companies", "map_computed_at")
    op.drop_column("companies", "map_y")
    op.drop_column("companies", "map_x")
