"""Company momentum ("heating up") score.

Revision ID: 0039
Revises: 0038
Create Date: 2026-07-13 00:00:00.000000

The compute-momentum stage scores every shown company's weekly "heating up"
momentum: a weight-renormalized mean over the present of three components —
news acceleration (company_snapshots.news_count_30d recent vs a trailing
baseline), funding recency (latest_round_date exponential decay), and headcount
growth (snapshot employee midpoints). The web /trending leaderboard ranks by it.

Stored as three nullable columns ON companies rather than a side table: momentum
is strictly 1:1 with a company (one weekly score), the dominant read — the
scored companies ordered by score — is a flat single-table WHERE + ORDER BY,
PostgREST-friendly with no RPC, mirroring the latest_round_* (0028) and map_*
(0038) denormalizations. The ranking inputs already live on companies.

- momentum_score (double precision, nullable) — [0, 1]; 0.5 = flat/neutral,
  higher = accelerating. NULL = insufficient data (no present component); the
  web hides such rows from /trending. Every processed shown company is
  (re)written each run so a company that loses its signal drops back to NULL
  rather than keeping a stale high score.
- momentum_computed_at (timestamptz, nullable) — per-company freshness stamp,
  re-stamped every run (even for a NULL score) as the "we evaluated this" marker.
- momentum_why (text[], nullable, default '{}') — pre-worded display chips
  ("news +180%", "raised 3wks ago", "+40% team"); the web joins with " · " and
  never re-computes. Default '{}' backfills existing rows so the column is never
  NULL in practice.

Indexed — UNLIKE map_x/map_y (0038), which are never a WHERE key. The /trending
read is ``WHERE momentum_score IS NOT NULL ORDER BY momentum_score DESC``, so a
PARTIAL DESC btree (only the scored minority; NULL rows excluded) both keeps the
index tiny and matches the sort order for an index-order scan.

Hand-written (not autogenerated) per the 0015+ convention — autogenerate cannot
model the partial/DESC index and silently drops it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0039"
down_revision: str | None = "0038"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies", sa.Column("momentum_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("momentum_computed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "momentum_why",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            server_default=sa.text("'{}'"),
        ),
    )
    # Partial DESC btree: only the scored rows (NULL excluded), sorted to match
    # the /trending read (WHERE momentum_score IS NOT NULL ORDER BY DESC).
    op.create_index(
        "ix_companies_momentum_score",
        "companies",
        [sa.text("momentum_score DESC")],
        postgresql_where=sa.text("momentum_score IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_companies_momentum_score", table_name="companies")
    op.drop_column("companies", "momentum_why")
    op.drop_column("companies", "momentum_computed_at")
    op.drop_column("companies", "momentum_score")
