"""career_moves — founder prior-employer edges (talent-flow rider)

Revision ID: 0040
Revises: 0039
Create Date: 2026-07-13 00:00:00.000000

Adds the career_moves table behind the per-company "Founder background /
notable alumni" rider. One row per (a company's founder/exec, a prior employer)
edge extracted from that company's scraped bios by the extract-career-history
stage — e.g. "SambaNova's Rodrigo Liang was previously at Oracle". The #184
career-history-probe found named pedigrees are thin (~13-18% of companies), so
most companies contribute zero rows (empty-not-fabricate); this schema-only PR
lands the table ahead of the writing stage (the 3-PR husk split: dispatch
workflow #185 → this migration → the version-gated apply stage).

Design:
- company_id FK CASCADE — the row belongs to the current company; indexed as the
  primary read path (the web rider does WHERE company_id = X).
- person_name (display) + person_normalized_name (match key). Deliberately NO FK
  to people.id: enrich wipes+re-inserts people every run, so an FK there would
  cascade-delete these rows on every enrichment. Keying to company_id +
  normalized name decouples this table from that churn. person_normalized_name
  is indexed to back the cross-company "repeat founders" lookup.
- prior_company_name — the prior employer, copied verbatim from the text.
- prior_company_id FK companies.id ON DELETE SET NULL, nullable — the in-catalog
  graph edge, set when the verbatim name resolves to one of our companies (Intel
  / IBM / a defunct startup stay NULL). SET NULL (not CASCADE): deleting the
  prior company must not delete the biographical fact, only drop the internal
  link. Indexed for the reverse "who came from company X" read.
- prior_role / start_year / end_year — best-effort, nullable (SmallInt years).
- source_url — provenance (every rendered fact is sourced): the scraped page.
- extraction_prompt_version — the prompt revision that produced the row; the
  stage version-gates re-extraction on it (NULL/older < current PROMPT_VERSION).
- UNIQUE (company_id, person_normalized_name, prior_company_name) — the
  idempotency key for the replace-style (DELETE by company_id, then INSERT)
  writer, so a re-run never duplicates an edge.

id carries a gen_random_uuid() server default (PG13+, as in 0019/0022) so a
set-based INSERT need not supply the PK; ORM inserts still provide it via the
model's uuid4 default.

Hand-written (not autogenerated) per the 0015+ convention so autogenerate's
spurious DROPs of the pg_trgm/partial indexes elsewhere don't sneak in.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0040"
down_revision: str | None = "0039"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "career_moves",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("person_name", sa.String(), nullable=False),
        sa.Column("person_normalized_name", sa.String(), nullable=False),
        sa.Column("prior_company_name", sa.String(), nullable=False),
        sa.Column(
            "prior_company_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
        sa.Column("prior_role", sa.String(), nullable=True),
        sa.Column("start_year", sa.SmallInteger(), nullable=True),
        sa.Column("end_year", sa.SmallInteger(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("extraction_prompt_version", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            ondelete="CASCADE",
            name="fk_career_moves_company_id",
        ),
        sa.ForeignKeyConstraint(
            ["prior_company_id"],
            ["companies.id"],
            ondelete="SET NULL",
            name="fk_career_moves_prior_company_id",
        ),
        sa.UniqueConstraint(
            "company_id",
            "person_normalized_name",
            "prior_company_name",
            name="uq_career_moves_company_person_prior",
        ),
    )
    op.create_index(
        "ix_career_moves_company_id",
        "career_moves",
        ["company_id"],
    )
    op.create_index(
        "ix_career_moves_person_normalized_name",
        "career_moves",
        ["person_normalized_name"],
    )
    op.create_index(
        "ix_career_moves_prior_company_id",
        "career_moves",
        ["prior_company_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_career_moves_prior_company_id", table_name="career_moves")
    op.drop_index(
        "ix_career_moves_person_normalized_name", table_name="career_moves"
    )
    op.drop_index("ix_career_moves_company_id", table_name="career_moves")
    op.drop_table("career_moves")
