"""career_extracted_prompt_version stamp on companies (talent-flow idempotency)

Revision ID: 0041
Revises: 0040
Create Date: 2026-07-13 00:00:00.000000

Adds ``companies.career_extracted_prompt_version`` — the per-company stamp that
makes extract-career-history idempotent. The career_moves rows alone cannot
distinguish "never extracted" from "extracted, correctly empty" (the ~85% of
companies with no named pedigree write ZERO rows), so without a stamp every run
would re-extract — and re-bill DeepSeek for — the empty majority. The stage
stamps this column with the prompt PROMPT_VERSION on every extraction attempt
(hit or empty) and selects on ``career_extracted_prompt_version IS NULL OR
< PROMPT_VERSION``, exactly mirroring enrichment_prompt_version /
--redescribe-outdated.

Indexed because it is the stage's selection WHERE key. Nullable with no default
so the whole existing catalog reads as "never extracted" and drains through the
bounded backfill once.

Hand-written (not autogenerated) per the 0015+ convention.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0041"
down_revision: str | None = "0040"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("career_extracted_prompt_version", sa.Text(), nullable=True),
    )
    op.create_index(
        "ix_companies_career_extracted_prompt_version",
        "companies",
        ["career_extracted_prompt_version"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_companies_career_extracted_prompt_version", table_name="companies"
    )
    op.drop_column("companies", "career_extracted_prompt_version")
