"""completeness_score + completeness_computed_at on companies (provenance UI)

Revision ID: 0042
Revises: 0041
Create Date: 2026-07-14 00:00:00.000000

Adds ``companies.completeness_score`` (Float, 0..1) + ``completeness_computed_at``
(timestamptz) — the per-company weighted-field completeness score, stored so the
web can render a positive-only "richly/well documented" provenance badge on
/c/[slug] WITHOUT re-implementing the scorer in TS. The score is written weekly
by the compute-completeness stage using ``util.completeness.completeness_score``
(the single source of truth, also aggregated by the data-quality report).

NOT indexed: read per-company for the page badge, never a WHERE/ORDER BY key
(unlike momentum_score's /trending leaderboard, which carries a partial DESC
index). Both columns nullable with no default, so the whole existing catalog
reads NULL ("not yet computed" → hidden badge) until the stage first runs — the
web read degrades to hidden, so this is migration-order-free on the web side.

Hand-written (not autogenerated) per the 0015+ convention.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0042"
down_revision: str | None = "0041"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("completeness_score", sa.Float(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "completeness_computed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("companies", "completeness_computed_at")
    op.drop_column("companies", "completeness_score")
