"""fact_verifications — DeepSeek source-verification verdicts

Revision ID: 0043
Revises: 0042
Create Date: 2026-07-15 00:00:00.000000

Adds the fact_verifications table behind the "✓ Verified against source"
enhancement (spec 2026-07-14-provenance-ui-design.md → source-verification). One
row per (company, rendered fact with a cited source_url) that the verify-sources
stage has checked against its source via DeepSeek: does the source SUPPORT the
claim? verdict ∈ supported | unsupported | uncertain, with a verbatim
supporting_quote for `supported` only. The web shows "✓ Verified against source"
for `supported` verdicts ONLY; `uncertain`/`unsupported` are never a public badge
(empty-not-fabricate — one false ✓ destroys the sourcing moat). An `unsupported`
verdict is a valuable internal data-quality signal.

Design:
- company_id FK CASCADE — the verdict belongs to the current company.
- fact_kind ('total_raised' | 'status' | 'funding_round') + fact_ref identify the
  fact within a company: company-level facts use fact_ref = ''; a funding round
  uses fact_ref = the round's id as text (so each round is distinguished).
  Deliberately NO FK to funding_rounds.id — extract-funding wipes+re-inserts
  rounds on reconcile, so an FK there would cascade-delete verifications on every
  funding refresh; the text ref decouples this table from that churn.
- source_url + claim record exactly what was verified (provenance + the value-gate
  the apply stage version-/value-gates re-verification on) and aid audit.
- verdict + supporting_quote (verbatim, nullable — set for 'supported' only).
- prompt_version — the source_verification.PROMPT_VERSION that produced the row;
  the stage re-verifies when it (or source_url / claim) changes.
- UNIQUE(company_id, fact_kind, fact_ref) — the idempotency/upsert key AND the web
  read path (WHERE company_id = X). No separate index: the composite's leading
  column covers the FK / company-scoped reads, and the table is small (~one row
  per verifiable fact). fact_kind / verdict are CHECK-constrained vocabularies
  (the codebase idiom, cf. funding_rounds.extraction_confidence).

id carries a gen_random_uuid() server default (PG13+, as in 0019/0022/0040) so a
set-based INSERT need not supply the PK; ORM inserts still provide it via the
model's uuid4 default.

Hand-written (not autogenerated) per the 0015+ convention so autogenerate's
spurious DROPs of the pg_trgm/partial indexes elsewhere don't sneak in.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0043"
down_revision: str | None = "0042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "fact_verifications",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("fact_kind", sa.String(), nullable=False),
        sa.Column(
            "fact_ref", sa.String(), nullable=False, server_default=""
        ),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("verdict", sa.String(), nullable=False),
        sa.Column("supporting_quote", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            ondelete="CASCADE",
            name="fk_fact_verifications_company_id",
        ),
        sa.CheckConstraint(
            "fact_kind IN ('total_raised', 'status', 'funding_round')",
            name="ck_fact_verifications_fact_kind",
        ),
        sa.CheckConstraint(
            "verdict IN ('supported', 'unsupported', 'uncertain')",
            name="ck_fact_verifications_verdict",
        ),
        sa.UniqueConstraint(
            "company_id",
            "fact_kind",
            "fact_ref",
            name="uq_fact_verifications_company_fact",
        ),
    )


def downgrade() -> None:
    op.drop_table("fact_verifications")
