"""news_articles.funding_round_id — the exact article→round link

Revision ID: 0044
Revises: 0043
Create Date: 2026-07-16 00:00:00.000000

The /c/[slug] timeline groups funding coverage under the round it covers.
Today that grouping is read-time date proximity (web lib/timeline.ts,
±14 days) plus a primary_news_url pin — which degrades to standalone news
rows for rounds with no announced_date (the Perplexity clutter case,
BACKLOG "Coverage grouping degrades on undated funding rounds").

This adds the exact link: extract-funding records which round each article's
extraction reconciled into, at the moment it knows (the reconcile call); a
set-based repair links historical articles whose url IS a round's
primary_news_url. Date proximity remains the read-time fallback for articles
neither path has linked.

Design:
- Nullable FK to funding_rounds.id with ON DELETE **SET NULL** — round rows
  can be deleted (repair-duplicate-rounds, dedup merges), and the link must
  never block that or dangle. A nulled link re-heals: the repair-catalog pass
  re-links by primary_news_url every cron, and the next extraction that
  reconciles the same round re-stamps it. (Contrast fact_verifications/0043,
  which needed the verdict to SURVIVE round churn and so avoided the FK;
  here the link is derived data — losing it costs nothing.)
- Indexed (ix_news_articles_funding_round_id) per the "index every FK"
  convention; the web read is by company_id, but the repair pass and the
  SET NULL bookkeeping both touch the FK column.

Hand-written (not autogenerated) per the 0015+ convention so autogenerate's
spurious DROPs of the pg_trgm/partial indexes elsewhere don't sneak in.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0044"
down_revision: str | None = "0043"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "news_articles",
        sa.Column("funding_round_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_news_articles_funding_round_id",
        "news_articles",
        "funding_rounds",
        ["funding_round_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_news_articles_funding_round_id",
        "news_articles",
        ["funding_round_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_news_articles_funding_round_id", table_name="news_articles")
    op.drop_constraint(
        "fk_news_articles_funding_round_id", "news_articles", type_="foreignkey"
    )
    op.drop_column("news_articles", "funding_round_id")
