"""companies.description_source + describe_fallback_prompt_version

Revision ID: 0045
Revises: 0044
Create Date: 2026-07-19 00:00:00.000000

The persisting apply path for describe-fallback (the third-party-grounded
description_short for the unscrapable / website-less residue — BACKLOG
2026-07-19 "missing-data residue"). The #243 dry-run probe cleared on prod
(18/25 described, 0 fabrication escapes); this migration adds the two columns
the apply path writes.

Design:
- description_source (nullable, NO default, NO backfill): provenance of the
  CURRENT description_short. NULL means the existing own-website enrich path
  wrote it (or the row is undescribed); 'fallback' means describe-fallback
  wrote it from third-party evidence. No default so the existing ~all-NULL
  cohort is left exactly as-is — NULL is a meaningful "own-website" state, not
  an "unknown" placeholder.
- describe_fallback_prompt_version (nullable): the per-company idempotency
  stamp, mirroring career_extracted_prompt_version. Stamped on every completed
  adjudication (described, deliberate null, or descriptor/claim rejection) so a
  company that correctly yields no description is not re-billed every run; the
  stage version-gates selection on it (NULL OR < PROMPT_VERSION), so a prompt
  bump re-selects everyone while stamped rows never re-bill.
- No indexes: both columns are read per-company on the row already loaded
  (never a WHERE key on a hot path); the stage's selection scans them as part
  of a bounded backlog drain, not a hot query. (Same reasoning the sibling
  prompt-version stamps use: unindexed except career's, which is a selection
  WHERE key at scale — this one filters a small residue cohort.)

Hand-written (not autogenerated) per the 0015+ convention so autogenerate's
spurious DROPs of the pg_trgm/partial indexes elsewhere don't sneak in.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0045"
down_revision: str | None = "0044"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "companies",
        sa.Column("description_source", sa.String(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("describe_fallback_prompt_version", sa.String(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("companies", "describe_fallback_prompt_version")
    op.drop_column("companies", "description_source")
