"""news_articles.text_refetched_at

Revision ID: 0046
Revises: 0045
Create Date: 2026-07-19 00:00:00.000000

The rotation stamp for the ``refetch-article-text`` stage (BACKLOG 2026-07-19
"article-text evidence widening"). Google-News-ingested rows whose stored
``raw_content`` is an interstitial stub (or a bare headline+snippet on a
resolution miss) starve describe-fallback / the entity guard / funding
extraction of real article prose. That stage re-resolves such a row to its
publisher page and heals ``raw_content`` in place.

Design:
- text_refetched_at (DateTime tz, nullable, NO default, NO backfill): when the
  refetch stage last ATTEMPTED this row (healed or not). NULL = never attempted.
  Stamped on every attempt — success, thin/failed fetch, or robots-block — so a
  permanently-thin article is not re-billed a live fetch every run; a future
  need can clear the stamp to force a retry. Mirrors the sibling rotation stamps
  (website_fallback_checked_at, describe_fallback_prompt_version).
- No index: the stage drains a bounded backlog with a small ``--limit`` slice,
  prominence-ordered by the owning company — a bounded scan on an on-demand
  lever, not a hot recurring WHERE key at scale. This matches migration 0045's
  describe_fallback_prompt_version (same bounded-drain reasoning, also
  unindexed); website_fallback_checked_at is indexed only because it gates the
  ~890-husk selection on the recurring 3h cron. The CLAUDE.md "index every
  WHERE column" rule carves out exactly this bounded-drain case (see 0045).

Hand-written (not autogenerated) per the 0015+ convention so autogenerate's
spurious DROPs of the pg_trgm/partial indexes elsewhere don't sneak in.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0046"
down_revision: str | None = "0045"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "news_articles",
        sa.Column("text_refetched_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("news_articles", "text_refetched_at")
